### ISSUE TITLE
The interface (frontend) needs to be worked on with more capabilities and more eye candy

### ISSUE THREAD

**Issue by Arabo-Hovsepian** [CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io#2]

**Comment by emil3h** [comment]
I plan on adding more input fields in addition to some CSS to make it look more appealing.

**Comment by emil3h** [comment]
https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/a46078bf3b870a27060d5fda2ca63ac1b5147df3
