### ISSUE TITLE
A database needs to be created so the information can be saved and retrieved when necessary

### ISSUE THREAD

**Issue by Arabo-Hovsepian** [CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io#3]

**Comment by emil3h** [comment]
I'll do some research to see how we can implement a database into our project. I'll start by looking into MongoDB.

**Comment by emil3h** [comment]
We realized that we could preform the desired functions of our website without using a database. I also asked the professor after class one day if a data base was mandatory, he said if you dont need it then thats fine. We ended up using PHP and apache on our AWS EC2 instance to create a new file for each user, as  a result creating a custom link.
