### ISSUE TITLE
More input fields need to be added to the frontend

### ISSUE THREAD

**Issue by Arabo-Hovsepian** [CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io#4]

**Comment by emil3h** [comment]
https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/92113cd39a13f385e0a3dc9a2635025cedf8c1c5

https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/05b4d2912e012586fa36f8d08c311fc8eb4ae7c9

https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/fd9b364aa2717ad06e52fd06630ccf4178ccb1d8
