### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by Arabo-Hovsepian** [CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io#5]
PHPUnit was selected as a testing framework

**Comment by emil3h** [comment]
https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/e61038b2300a11cc3f2759f8593b81f65243c568

https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/032708eaef8f4f708b5e6fb9e8917b8f34898dd1

https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/15cf8b33b9b6c8cea611797a347481a0c0269917

https://github.com/CS-4800-Brotherhood-of-Hearts/PG_Portfolio_Generator.github.io/commit/f270a557e8952a8dac0b088266d06e4590841716
